USE northwind;

SELECT id, shipping_fee, 
ROW_NUMBER() OVER (PARTITION BY shipping_fee ORDER BY shipping_fee ASC) as row_num
FROM orders ORDER BY shipping_fee DESC;

SELECT id, shipping_fee, 
RANK() OVER (ORDER BY shipping_fee DESC) as shipping_fee_rank 
FROM orders;

SELECT id, shipping_fee, 
DENSE_RANK() OVER (ORDER BY shipping_fee DESC) as shipping_fee_rank 
FROM orders;

SELECT id, shipping_fee, 
NTILE(4) OVER (ORDER BY shipping_fee DESC) as quartile 
FROM orders;

USE shop;

SELECT ORDER_ID, ODATE, AMT, LAG(AMT) OVER(ORDER BY ODATE) AS prev_amt FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, (AMT - LAG(AMT) OVER(ORDER BY ODATE)) AS prev_amt FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, LEAD(AMT) OVER(ORDER BY ODATE) AS next_amt FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, (LEAD(AMT) OVER(ORDER BY ODATE) - AMT) AS next_amt FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, 
FIRST_VALUE(AMT) OVER(PARTITION BY EXTRACT(YEAR FROM ODATE), EXTRACT(MONTH FROM ODATE) 
ORDER BY ODATE) AS first_v FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, 
LAST_VALUE(AMT) OVER(PARTITION BY EXTRACT(YEAR FROM ODATE), EXTRACT(MONTH FROM ODATE) 
ORDER BY ODATE) AS first_v FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, 
NTH_VALUE(AMT, 3) OVER(PARTITION BY EXTRACT(YEAR FROM ODATE), EXTRACT(MONTH FROM ODATE) 
ORDER BY ODATE) AS first_v FROM ORDERS;