USE shop;

SELECT ORDER_ID, ODATE, AMT, 
SUM(AMT) OVER(ORDER BY ODATE) AS cumilative_sum_to_date 
FROM ORDERS;

SELECT ORDER_ID, ODATE, AMT, 
COUNT(ORDER_ID) OVER (ORDER BY ODATE, ORDER_ID) AS cumulative_order_count_to_date 
FROM ORDERS ORDER BY ODATE, ORDER_ID;